<!DOCTYPE html>
<html lang="id">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Riwayat Absensi</title>
    <link
      href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap"
      rel="stylesheet"
    />
    <!-- Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
  </head>
  <body class="bg-gray-50">
    <div class="min-h-screen p-6 max-w-2xl mx-auto">
      <!-- Header -->
      <div class="mb-6">
        <a
          href="#"
          onclick="window.history.back(); return false;"
          class="text-blue-600 hover:text-blue-700 text-sm font-medium mb-2 inline-block"
        >
          ← Kembali
        </a>

        <div class="flex items-center justify-between">
          <div>
            <h1 class="text-3xl font-bold text-gray-800">Riwayat Absensi</h1>
            <p class="text-gray-600 mt-1">
              {{$karyawan->nama}} - {{$karyawan->jabatan->nama}}
            </p>
          </div>
        </div>
      </div>

      <!-- Summary Stats -->
      <div class="mb-6 grid grid-cols-3 md:grid-cols-5 gap-3">
        <div class="bg-white rounded-lg shadow-sm border border-gray-100 p-3">
          <p class="text-xs text-gray-600 mb-1">Hadir</p>
          <p class="text-xl font-bold text-green-600">{{ $stats["hadir"] + $stats['setengah_hari'] }}</p>
          @if($stats['setengah_hari'] > 0)
          <p class="text-[10px] text-gray-500 mt-auto pt-1 flex items-center">
            <span class="inline-block w-1.5 h-1.5 rounded-full bg-yellow-500 mr-1"></span>
            <span>{{ $stats['setengah_hari'] }} Setengah Hari</span>
          </p>
          @endif
        </div>
        <div class="bg-white rounded-lg shadow-sm border border-gray-100 p-3 flex flex-col">
          <p class="text-xs text-gray-600 mb-1">Terlambat</p>
          <p class="text-xl font-bold text-orange-600">
            {{ $stats["terlambat"] }}
          </p>
        </div>
        <div class="bg-white rounded-lg shadow-sm border border-gray-100 p-3 flex flex-col">
          <p class="text-xs text-gray-600 mb-1">Izin</p>
          <p class="text-xl font-bold text-blue-600">{{ $stats["izin"] }}</p>
        </div>
        <div class="bg-white rounded-lg shadow-sm border border-gray-100 p-3 flex flex-col">
          <p class="text-xs text-gray-600 mb-1">Sakit</p>
          <p class="text-xl font-bold text-purple-600">
            {{ $stats["sakit"] }}
          </p>
        </div>
        <div class="bg-white rounded-lg shadow-sm border border-gray-100 p-3 flex flex-col">
          <p class="text-xs text-gray-600 mb-1">Alpha</p>
          <p class="text-xl font-bold text-red-600">{{ $stats["alpha"] }}</p>
        </div>
      </div>

      <!-- Calendar Card -->
      <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
        <!-- Calendar Header -->
        <div class="flex flex-col items-center justify-between gap-4 mb-6">
          <form id="monthForm" class="flex items-center gap-3">
            <input
              type="month"
              id="month-picker"
              name="month"
              value="{{ $monthYear ?? '' }}"
              class="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition-all"
            />
            <button
              type="submit"
              class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium"
            >
              Tampilkan
            </button>
          </form>
        </div>

        <!-- Calendar Grid -->
        <div class="grid grid-cols-7 gap-2">
          <!-- Day Headers -->
          <div class="text-center py-3 text-sm font-semibold text-gray-600">
            Min
          </div>
          <div class="text-center py-3 text-sm font-semibold text-gray-600">
            Sen
          </div>
          <div class="text-center py-3 text-sm font-semibold text-gray-600">
            Sel
          </div>
          <div class="text-center py-3 text-sm font-semibold text-gray-600">
            Rab
          </div>
          <div class="text-center py-3 text-sm font-semibold text-gray-600">
            Kam
          </div>
          <div class="text-center py-3 text-sm font-semibold text-gray-600">
            Jum
          </div>
          <div class="text-center py-3 text-sm font-semibold text-gray-600">
            Sab
          </div>

          <!-- Calendar Days -->
          <div id="calendarDays" class="col-span-7 grid grid-cols-7 gap-2">
            <!-- Days will be generated by JavaScript -->
          </div>
        </div>

        <!-- Legend -->
        <div class="mt-8 pt-6 border-t border-gray-200">
          <h3 class="text-sm font-semibold text-gray-700 mb-3">Keterangan:</h3>
          <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-3">
            <div class="flex items-center">
              <div class="w-4 h-4 rounded bg-green-500 mr-2"></div>
              <span class="text-sm text-gray-600">Hadir</span>
            </div>
            <div class="flex items-center">
              <div class="w-4 h-4 rounded bg-orange-500 mr-2"></div>
              <span class="text-sm text-gray-600">Terlambat</span>
            </div>
            <div class="flex items-center">
              <div class="w-4 h-4 rounded bg-purple-500 mr-2"></div>
              <span class="text-sm text-gray-600">Sakit</span>
            </div>
            <div class="flex items-center">
              <div class="w-4 h-4 rounded bg-blue-500 mr-2"></div>
              <span class="text-sm text-gray-600">Izin</span>
            </div>
            <div class="flex items-center">
              <div class="w-4 h-4 rounded bg-yellow-500 mr-2"></div>
              <span class="text-sm text-gray-600">Setengah Hari</span>
            </div>
            <div class="flex items-center">
              <div class="w-4 h-4 rounded bg-red-500 mr-2"></div>
              <span class="text-sm text-gray-600">Alpha</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
      const month = @json($month)
    </script>
    <script>
      const monthData = document.getElementById('month-picker').value.split('-')
      let currentMonth  = Number(monthData[1]); // November (1-indexed untuk display)
      let currentYear   = Number(monthData[0]);

      const absensiData = @json($absens)

      const monthNames = [
        "Januari",
        "Februari",
        "Maret",
        "April",
        "Mei",
        "Juni",
        "Juli",
        "Agustus",
        "September",
        "Oktober",
        "November",
        "Desember",
      ];

      function getStatusColor(status, isLate) {
        if (isLate) return "bg-orange-500";
        switch (status) {
          case "Hadir":
            return "bg-green-500";
          case "Sakit":
            return "bg-purple-500";
          case "Izin":
            return "bg-blue-500";
          case "Alpha":
            return "bg-red-300";
          case "Setengah Hari":
            return "bg-yellow-500";
          default:
            return "";
        }
      }

      function renderCalendar() {
        const firstDay = new Date(currentYear, currentMonth - 1, 1);
        const lastDay = new Date(currentYear, currentMonth, 0);
        const prevLastDay = new Date(currentYear, currentMonth - 1, 0);

        const firstDayIndex = firstDay.getDay();
        const lastDayDate = lastDay.getDate();
        const prevLastDayDate = prevLastDay.getDate();

        let days = "";

        // Previous month days
        for (let x = firstDayIndex; x > 0; x--) {
          days += `
                    <div class="aspect-square flex items-center justify-center text-gray-300">
                        ${prevLastDayDate - x + 1}
                    </div>
                `;
        }

        // Current month days
        for (let i = 1; i <= lastDayDate; i++) {
          const dateStr = `${currentYear}-${String(currentMonth).padStart(
            2,
            "0"
          )}-${String(i).padStart(2, "0")}`;
          const absen = absensiData[dateStr];
          const today = new Date();
          const isToday =
            i === today.getDate() &&
            currentMonth - 1 === today.getMonth() &&
            currentYear === today.getFullYear();

          let dayClass =
            "aspect-square flex flex-col items-center justify-center rounded-lg transition-all hover:shadow-md cursor-pointer";
          let borderClass = isToday ? "ring-2 ring-blue-500" : "";
          let bgClass = "";
          let textClass = "text-gray-700 font-medium";
          let dotHtml = "";

          if (absen) {
            bgClass = "bg-gray-50";
            const colorClass = getStatusColor(absen.status, absen.isLate);
            dotHtml = `<div class="w-2 h-2 rounded-full ${colorClass} mt-1"></div>`;
          }

          days += `
                    <div class="${dayClass} ${borderClass} ${bgClass}" title="${
            absen ? absen.status : "Tidak ada data"
          }">
                        <span class="${textClass}">${i}</span>
                        ${dotHtml}
                    </div>
                `;
        }

        // Next month days
        const totalCells = days.split("</div>").length - 1;
        const nextDays = 42 - totalCells; // 6 rows * 7 days
        for (let j = 1; j <= nextDays; j++) {
          days += `
                    <div class="aspect-square flex items-center justify-center text-gray-300">
                        ${j}
                    </div>
                `;
        }

        document.getElementById("calendarDays").innerHTML = days;
      }



      renderCalendar();
    </script>
  </body>
</html>
